version: '2.3'
services:


  # The Application
  app:
    build:
      context: ./.docker
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.docker/xdebug.ini:/etc/php/7.4/mods-available/xdebug.ini
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
      - "PHP_IDE_CONFIG=serverName=dock"

  # The Application
  cli:
    build:
      context: ./.docker
      dockerfile: cli.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
      - "PHP_IDE_CONFIG=serverName=dock"

  # The Web Server
  web:
    build:
      context: ./.docker
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 80:80

  # The Database
  database:
    image: webhippie/mariadb
    volumes:
      - dbdata:/var/lib/mysql
      - dbconf:/etc/mysql/conf.d
    environment:
      MARIADBL_DATABASE: drupal
      MARIADB_USERNAME: drupal
      MARIADB_PASSWORD: drupal
      MARIADB_ROOT_PASSWORD: drupal
    ports:
      - "33061:3306"

  node:
    container_name: ricardoanalytic_node_server
    build:
      context: .
      dockerfile: .docker/node.dockerfile
    ports:
      - "8080:8080"
    volumes_from:
      - app
    networks:
      - default

  redis:
    image: redis
    volumes:
      - redis:/data
    ports:
      - "63791:6379"

volumes:
  dbdata:
  dbconf:
  redis: