<?php

/**
 * @file
 * Contains ra_admin.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ra_admin_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ra_admin module.
    case 'help.page.ra_admin':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Various stuff') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ra_admin_theme() {
  return [
    'status_block' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],
  ];
}
