<?php

/**
 * @file
 * Contains ra_item.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Queue\QueueFactory;
use Drupal\Core\Queue\QueueInterface;

/**
 * Implements hook_help().
 */
function ra_item_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ra_item module.
    case 'help.page.ra_item':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Item') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_cron().
 */
function ra_item_cron() {
  $nids = _ra_seller_get_nodes();

  /** @var QueueFactory $queue_factory */
  $queue_service = \Drupal::service('queue');
  /** @var QueueInterface $queue_item */
  $queue_item = $queue_service->get('item_rating_queue');

  foreach ($nids as $nid) {
    $data['seller_nid'] = $nid;
    //    $queue_item->createItem($data);
  }
}
