<?php

/**
 * @file
 * Contains ra_seller.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\Node;
use Drupal\ra_seller\Plugin\QueueWorker\SellerArticleQueue;

/**
 * Implements hook_cron().
 */
function ra_seller_cron() {
  $seller_nids = _ra_seller_get_nodes();
  _ra_seller_update_data($seller_nids);
}

/**
 * Updates the seller information.
 */
function _ra_seller_update_data($seller_nids) {
  /** @var Drupal\Core\Queue\QueueFactory $queue_factory */
  $queue_service = Drupal::service('queue');

  /** @var Drupal\Core\Queue\QueueInterface $seller_queue */
  $seller_queue = $queue_service->get('seller_queue');

  /** @var Drupal\Core\Queue\QueueInterface $seller_article_queue */
  $seller_article_queue = $queue_service->get('seller_article_queue');

  foreach ($seller_nids as $nid) {
    $sellerNode = Node::load($nid);
    $data['nid'] = $nid;

    // Seller's articles.
    $last = \Drupal::state()->get('seller_article_last_process__' . $sellerNode->id());
    if ($last < strtotime(SellerArticleQueue::ARTICLE_RECRAWLE_THRESHOLD)) {
      $seller_article_queue->createItem($data);
    }

    // Seller information.
    // Process if older than 2 weeks or init.
    if ($sellerNode->field_seller_init_process->value || $sellerNode->getChangedTime() < strtotime('-2 week')) {
      $seller_queue->createItem($data);
    }
  }

}

/**
 * Add seller to to given queue.
 */
function _ra_seller_get_nodes() {
  return Drupal::entityQuery('node')
    ->condition('type', 'seller')
    ->condition('status', 1)
    ->execute();
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function ra_seller_node_presave(EntityInterface $entity) {
  if ($entity->bundle() === 'seller') {
    // The seller_id is node label.
    $entity->field_seller_id->value = $entity->label();

    if ($entity->isNew()) {
      $entity->field_seller_init_process = 1;
    }
  }
}
