<?php

/**
 * @file
 * Contains ra_seller.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Queue\QueueFactory;
use Drupal\Core\Queue\QueueInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ra_seller_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ra_seller module.
    case 'help.page.ra_seller':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Seller') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_cron().
 */
function ra_seller_cron() {
  $nids = _ra_seller_get_nodes();

  /** @var QueueFactory $queue_factory */
  $queue_service = \Drupal::service('queue');
  /** @var QueueInterface $queue_item */
  $queue_item = $queue_service->get('seller_queue');

  foreach ($nids as $nid) {
    $data['nid'] = $nid;
    $queue_item->createItem($data);
  }
}

/**
 * Add seller to to given queue;
 */
function _ra_seller_get_nodes() {
  $nids = \Drupal::entityQuery('node')
    ->condition('type', 'seller')
    ->condition('status', 1)
    ->execute();

  return $nids;
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function ra_seller_node_presave(EntityInterface $entity) {
  if ($entity->bundle() === 'seller') {
    // seller_id is node label.
    $entity->field_seller_id->value = $entity->label();
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function ra_seller_node_insert(EntityInterface $entity) {
  if ($entity->bundle() === 'seller') {
    $entity->field_seller_init_process->value = 1;
  }
}
