<?php

/**
 * @file
 * Contains ra_rating.module.
 */

/**
 * Implements hook_cron().
 */
function ra_rating_cron() {
  $nids = _ra_seller_get_nodes();

  /** @var Drupal\Core\Queue\QueueFactory $queue_factory */
  $queue_service = Drupal::service('queue');
  /** @var Drupal\Core\Queue\QueueInterface $queue_item */
  $queue_item = $queue_service->get('rating_queue');

  foreach ($nids as $nid) {
    $data['seller_nid'] = $nid;
    $queue_item->createItem($data);
  }
}
